### ISSUE TITLE
Build in Cam Bravia KD-55X9005B

### ISSUE THREAD

**Issue by vgr28** [alanreid/bravia#12]
Hi, would it be possible to have access to cam? Cam was only supported by Skype APP, but this is not supported any more. So I'm thinking about to use the cam for Smarthome stuff...

**Comment by alanreid** [comment]
Hi @vgr28,

I have honestly no idea, but you're welcome to give it a try of course. You can see if they're any related commands listed with `getCommandNames()`. My guess is that the cam is probably only accessible from an app context only.

Best,
Alan
