### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mschwartz** [alanreid/bravia#13]
Looking at the code, the examples are completely wrong, no?

You have implemented ES6 style classes with a static discover() method, though it looks like  you can new Bravia() with a known IP and it works.

The new ES6 way seems much more elegant.

**Comment by mschwartz** [comment]
My bad.

npm install bravia 

installed something else.

**Comment by alanreid** [comment]
Ok, no worries! 

Yeah, this is a few years old and I don't really maintain this anymore to be honest. I don't own a Bravia TV anymore and I have no way of testing things myself, so I merged some PRs only based on people telling me it worked.

The npm version you installed is probably the one I originally uploaded. At least I know that one worked fine in the TV model I was using.

Sorry for the confusion!

**Comment by mschwartz** [comment]
I'm working on some home automation software for my house.  Totally custom.

I have an LGTV, two Samsung TVs (computer monitors), and 2 Sony TVs.  I'm working on the Sony TV integration right now.

TiVo looks like this (Sony and LGTV are similar but direct control the TV):

![image](https://user-images.githubusercontent.com/329637/28036147-0ec2bb40-656c-11e7-98a7-810831756b87.png)

**Comment by alanreid** [comment]
Wow, that looks awesome! Hope it all works as expected then!

**Comment by mschwartz** [comment]
I got the Bravia logic working (mostly):

![image](https://user-images.githubusercontent.com/329637/28071857-13d711ea-6606-11e7-9083-852cd8c6441f.png)

**Comment by mschwartz** [comment]
Once the thing is fully functional, I'll do a lot of refactoring and enhancement of the graphics.
