### ISSUE TITLE
Start Netflix film

### ISSUE THREAD

**Issue by eliasbnr** [alanreid/bravia#16]
hey,

how can I start a movie directly in netflix?

best regards
Elias Bennour

**Comment by alanreid** [comment]
Hey Elias,

As far as this works, you can only start Netflix and trigger some remote control buttons (like arrows, etc). So other than getting there simulating button presses, you can’t. Don’t know if it helps, but could still be an option.

**Comment by eliasbnr** [comment]
Hey,

Thanks for the answer. it is somehow possible to add this function?

**Comment by alanreid** [comment]
Hm no, I don't think it is unfortunately. As far as I know at least!
