### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by villaocho** [alanreid/bravia#2]
Hi Alan,
An error is happening =

npm ERR! socketwatcher@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.```

Node Version v4.1.2

**Comment by alanreid** [comment]
Hi @villaocho,

Thanks for reporting this. I think this might be related to #1. Could you confirm? I'll try to reproduce the error and fix it.

**Comment by alanreid** [comment]
Hi @villaocho,

This has been fixed in #1. Could you please try again?

Thanks!
